// Evalscript Sentinel Hub — Sentinel-2 L2A
// Formato CDSE: dataMask in input + output separato + SCL per nuvole

export const EVALSCRIPTS: Record<string, string> = {

  NDVI: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B04", "B08", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["NDVI"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B08+s.B04)===0 ? 0 : (s.B08-s.B04)/(s.B08+s.B04);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

  NDMI: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B8A", "B11", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["NDMI"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B8A+s.B11)===0 ? 0 : (s.B8A-s.B11)/(s.B8A+s.B11);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

  NBR: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B08", "B12", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["NBR"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B08+s.B12)===0 ? 0 : (s.B08-s.B12)/(s.B08+s.B12);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

  NDBI: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B08", "B11", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["NDBI"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B11+s.B08)===0 ? 0 : (s.B11-s.B08)/(s.B11+s.B08);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

  EVI: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B02", "B04", "B08", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["EVI"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B08+6*s.B04-7.5*s.B02+10000)===0 ? 0 : 2.5*(s.B08-s.B04)/(s.B08+6*s.B04-7.5*s.B02+10000);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

  BREI: [
    '//VERSION=3',
    'function setup() {',
    '  return {',
    '    input: [{ bands: ["B04", "B11", "SCL", "dataMask"] }],',
    '    output: [',
    '      { id: "default", bands: ["BREI"] },',
    '      { id: "dataMask", bands: 1 }',
    '    ]',
    '  };',
    '}',
    'function evaluatePixel(s) {',
    '  var val = (s.B11+s.B04)===0 ? 0 : (s.B11-s.B04)/(s.B11+s.B04);',
    '  var scl = s.SCL;',
    '  var valid = (scl===4||scl===5||scl===6||scl===7||scl===11) ? 1 : 0;',
    '  return { default: [val], dataMask: [s.dataMask && valid] };',
    '}',
  ].join('\n'),

}
